name = "civics2026"
main = "src/worker.ts" 
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "civics2026-production"
database_id = "93488a89-9448-4cb9-998b-e4fad7b045aa"
migrations_dir = "migrations"
[assets]
directory = "./dist"
[vars]
TEACHER_PASSWORD = "0512"
